[variables]
NODE_VERSION = "18"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm ci --no-audit --no-fund",
    "npm run build"
]

[phases.build]
cmds = ["node verify-build.cjs"]

[start]
cmd = "node build" 