[variables]
NODE_VERSION = "18"
NPM_VERSION = "latest"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "npm ci --ignore-scripts",
    "npm run build"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "node build" 